backgrounds = {
    "screen_1": "fondo-inicio.png",
    "screen_2": "fondo-inicio.png",
    "screen_3": "fondo-plantas.png",
    "screen_4": "fondo-partes-2.png",
    "screen_5": "fondo-repro.png",
    "screen_6": "fondo-repro-2.png",
    "screen_8": "fondo-agri.png",
    "screen_9": "fondo-mapa-2.png",
    "screen_10": "fondo-acc.png",
    "screen_11": "fondo-plantas.png",
}

banners = {
    "banner-inf": {
        "coordinates": (0, 432),
        "filename": "banner-inf.png",
    },
    "banner-plantas": {
        "coordinates": (0, 0),
        "filename": "banner-plantas.png",
    },
    "banner-partes": {
        "coordinates": (0, 0),
        "filename": "banner-partes.png",
    },
    "banner-repro": {
        "coordinates": (0, 0),
        "filename": "banner-repro.png",
    },
    "banner-agri": {
        "coordinates": (0, 0),
        "filename": "banner-agri.png",
    },
    "banner-siembra": {
        "coordinates": (0, 0),
        "filename": "banner-siembra.png",
    },
    "banner-glo": {
        "coordinates": (0, 0),
        "filename": "banner-glo.png",
    },
    "banner-or": {
        "coordinates": (0, 0),
        "filename": "banner-or.png",
    },
    "banner-or-es": {
        "coordinates": (0, 0),
        "filename": "banner-or-es.png",
    },
    "banner-or-pa": {
        "coordinates": (0, 0),
        "filename": "banner-or-pa.png",
    },
    "banner-or-doc": {
        "coordinates": (0, 0),
        "filename": "banner-or-doc.png",
    },
    "banner-acc-visual": {
        "coordinates": (0, 0),
        "filename": "banner-acc-visual.png",
    },
    "banner-acc-sordo": {
        "coordinates": (0, 0),
        "filename": "banner-acc-sordo.png",
    },
}

images = {"f1": "f1.png"}

animations = {
    "animation-3": {
        "coordinates": (100, 200),
        "columns": 8,
        "rows": 1,
        "colorkey": -1,
        "loop": True,
        "frames": 5,
        "filename": "animation-3.png",
    },
    "animation-4": {
        "coordinates": (0, 50),
        "columns": 8,
        "rows": 1,
        "colorkey": -1,
        "loop": True,
        "frames": 10,
        "filename": "animation-4.png",
    },
    "animation-4-1": {
        "coordinates": (430, 100),
        "columns": 5,
        "rows": 1,
        "colorkey": -1,
        "loop": False,
        "frames": 10,
        "filename": "animation-4-1.png",
    },
    "animation-4-2": {
        "coordinates": (430, 100),
        "columns": 9,
        "rows": 1,
        "colorkey": -1,
        "loop": False,
        "frames": 10,
        "filename": "animation-4-2.png",
    },
    "animation-4-3": {
        "coordinates": (430, 100),
        "columns": 10,
        "rows": 1,
        "colorkey": -1,
        "loop": False,
        "frames": 10,
        "filename": "animation-4-3.png",
    },
    "animation-4-4": {
        "coordinates": (430, 100),
        "columns": 6,
        "rows": 1,
        "colorkey": -1,
        "loop": False,
        "frames": 10,
        "filename": "animation-4-4.png",
    },
    "animation-5": {
        "filename": "animation-5.png",
        "columns": 8,
        "rows": 1,
        "coordinates": (50, 50),
        "colorkey": -1,
        "loop": True,
        "frames": 10,
    },
    "animation-5-0": {
        "filename": "animation-5-0.png",
        "columns": 7,
        "rows": 1,
        "coordinates": (560, 235),
        "colorkey": -1,
        "loop": False,
        "frames": 10,
    },
    "animation-5-1": {
        "filename": "animation-5-1.png",
        "columns": 7,
        "rows": 1,
        "coordinates": (620, 235),
        "colorkey": -1,
        "loop": False,
        "frames": 10,
    },
    "animation-5-2": {
        "filename": "animation-5-2.png",
        "columns": 7,
        "rows": 1,
        "coordinates": (520, 235),
        "colorkey": -1,
        "loop": False,
        "frames": 10,
    },
    "animation-5-3": {
        "filename": "animation-5-3.png",
        "columns": 8,
        "rows": 1,
        "coordinates": (530, 250),
        "colorkey": None,
        "loop": False,
        "frames": 12,
    },
    "animation-6": {
        "filename": "animation-6.png",
        "columns": 3,
        "rows": 1,
        "coordinates": (630, 50),
        "colorkey": -1,
        "loop": True,
        "frames": 10,
    },
    "animation-6-2": {
        "filename": "animation-6-2.png",
        "columns": 3,
        "rows": 1,
        "coordinates": (50, 200),
        "colorkey": -1,
        "loop": True,
        "frames": 10,
    },
    "animation-6-3": {
        "filename": "animation-6-3.png",
        "columns": 1,
        "rows": 1,
        "coordinates": (100, 100),
        "colorkey": -1,
        "loop": True,
        "frames": 2,
    },
    "animation-6-4": {
        "filename": "animation-6-4.png",
        "columns": 4,
        "rows": 1,
        "coordinates": (350, 80),
        "colorkey": -1,
        "loop": False,
        "frames": 18,
    },
    "animation-6-5": {
        "filename": "animation-6-5.png",
        "columns": 4,
        "rows": 1,
        "coordinates": (350, 80),
        "colorkey": -1,
        "loop": False,
        "frames": 22,
    },
    "animation-6-6": {
        "filename": "animation-6-6.png",
        "columns": 6,
        "rows": 1,
        "coordinates": (350, 80),
        "colorkey": -1,
        "loop": False,
        "frames": 18,
    },
    "animation-8": {
        "filename": "animation-8.png",
        "columns": 5,
        "rows": 1,
        "coordinates": (130, 110),
        "colorkey": -1,
        "loop": True,
        "frames": 8,
    },
    "animation-8-0": {
        "filename": "animation-8-0.png",
        "columns": 1,
        "rows": 1,
        "coordinates": (700, 150),
        "colorkey": -1,
        "loop": False,
        "frames": 18,
    },
    "colors-woman": {
        "filename": "colors-woman.png",
        "columns": 9,
        "rows": 3,
        "coordinates": (730, 160),
        "colorkey": (21, 76, 75),
        "loop": True,
        "frames": 4,
    },
    "colors-man": {
        "filename": "colors-man.png",
        "columns": 9,
        "rows": 3,
        "coordinates": (730, 160),
        "colorkey": (21, 76, 75),
        "loop": True,
        "frames": 4,
    },
}

popups = {}

buttons = {
    "nino": {
        "coordinates": (400, 150),
        "tooltip": "Siembra la semilla",
        "filename": "boton-nino.png",
        "frames": 8,
        "colorkey": None,
        "loop": True,
        "frame_speed": 12,
    },
    "nina": {
        "coordinates": (570, 150),
        "tooltip": "Plantas y números",
        "filename": "boton-nina.png",
        "frames": 8,
        "colorkey": None,
        "loop": True,
        "frame_speed": 12,
    },
    "plantas": {
        "coordinates": (0, 80),
        "tooltip": "Las plantas",
        "filename": "boton-plantas.png",
        "frames": 8,
        "colorkey": None,
        "loop": True,
        "frame_speed": 8,
    },
    "repro": {
        "coordinates": (700, 180),
        "tooltip": "Reproducción de las plantas",
        "filename": "boton-repro.png",
        "frames": 8,
        "colorkey": None,
        "loop": False,
        "frame_speed": 8,
    },
    "agri": {
        "coordinates": (270, 185),
        "tooltip": "La agricultura en Venezuela",
        "filename": "boton-agri.png",
        "frames": 4,
        "colorkey": None,
        "loop": False,
        "frame_speed": 8,
    },
    "config": {
        "coordinates": (60, 445),
        "tooltip": "Accesibilidad",
        "filename": "boton-acc.png",
        "frames": 3,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "orientacion": {
        "coordinates": (884, 440),
        "tooltip": "Orientaciones y sugerencias",
        "filename": "boton-or.png",
        "frames": 3,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "home": {
        "coordinates": (889, 440),
        "tooltip": "Menú",
        "filename": "boton-menu.png",
        "frames": 3,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "sig": {
        "coordinates": (560, 440),
        "tooltip": "Avanzar",
        "filename": "boton-avanzar.png",
        "frames": 3,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "volver": {
        "coordinates": (320, 445),
        "tooltip": "Regresar",
        "filename": "boton-regresar.png",
        "frames": 3,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "puerta": {
        "coordinates": (60, 425),
        "tooltip": "Regresar",
        "filename": "boton-puerta.png",
        "frames": 3,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "guardar": {
        "coordinates": (860, 445),
        "tooltip": "Guardar",
        "filename": "boton-guardar.png",
        "frames": 3,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "boton_sordo": {
        "coordinates": (300, 440),
        "tooltip": "Discapacidad auditiva",
        "filename": "boton-sordo.png",
        "frames": 3,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "boton_visual": {
        "coordinates": (483, 430),
        "tooltip": "Discapacidad visual",
        "filename": "boton-visual.png",
        "frames": 3,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "inicio": {
        "coordinates": (650, 440),
        "tooltip": "Inicio",
        "filename": "boton-inicio.png",
        "frames": 3,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "boton_or_ninos": {
        "coordinates": (300, 440),
        "tooltip": "Orientaciones a la niña, niño y adolescente",
        "filename": "boton-or-es.png",
        "frames": 3,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "boton_or_docentes": {
        "coordinates": (500, 440),
        "tooltip": "Sugerencias pedagógicas",
        "filename": "boton-or-doc.png",
        "frames": 3,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "boton_or_padres": {
        "coordinates": (700, 440),
        "tooltip": "Orientaciones a la adulta y al adulto responsable",
        "filename": "boton-or-pa.png",
        "frames": 3,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "boton_or_padres": {
        "coordinates": (700, 440),
        "tooltip": "Orientaciones a la adulta y al adulto responsable",
        "filename": "boton-or-pa.png",
        "frames": 3,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "onmag": {
        "coordinates": (130, 120),
        "tooltip": "none",
        "filename": "cuadro.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "onmag_si": {
        "coordinates": (130, 120),
        "tooltip": "none",
        "filename": "cuadro-1.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "offmag": {
        "coordinates": (245, 120),
        "tooltip": "none",
        "filename": "cuadro.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "offmag_si": {
        "coordinates": (245, 120),
        "tooltip": "none",
        "filename": "cuadro-1.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "tam18": {
        "coordinates": (130, 200),
        "tooltip": "none",
        "filename": "cuadro.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "tam18_sel": {
        "coordinates": (130, 200),
        "tooltip": "none",
        "filename": "cuadro-1.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "tam20": {
        "coordinates": (210, 200),
        "tooltip": "none",
        "filename": "cuadro.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "tam20_sel": {
        "coordinates": (210, 200),
        "tooltip": "none",
        "filename": "cuadro-1.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "tam22": {
        "coordinates": (290, 200),
        "tooltip": "none",
        "filename": "cuadro.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "tam22_sel": {
        "coordinates": (290, 200),
        "tooltip": "none",
        "filename": "cuadro-1.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "lector": {
        "coordinates": (130, 295),
        "tooltip": "none",
        "filename": "cuadro.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "lector_si": {
        "coordinates": (130, 295),
        "tooltip": "none",
        "filename": "cuadro-1.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "oflector": {
        "coordinates": (245, 295),
        "tooltip": "none",
        "filename": "cuadro.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "oflector_si": {
        "coordinates": (245, 295),
        "tooltip": "none",
        "filename": "cuadro-1.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "vbaja": {
        "coordinates": (93, 390),
        "tooltip": "none",
        "filename": "cuadro.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "vbaja_sel": {
        "coordinates": (93, 390),
        "tooltip": "none",
        "filename": "cuadro-1.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "vmedia": {
        "coordinates": (208, 390),
        "tooltip": "none",
        "filename": "cuadro.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "vmedia_sel": {
        "coordinates": (208, 390),
        "tooltip": "none",
        "filename": "cuadro-1.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "vrapida": {
        "coordinates": (332, 390),
        "tooltip": "none",
        "filename": "cuadro.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "vrapida_sel": {
        "coordinates": (332, 390),
        "tooltip": "none",
        "filename": "cuadro-1.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "velocidad": {
        "coordinates": (440, 360),
        "tooltip": "none",
        "filename": "velocidad.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "si": {
        "coordinates": (430, 120),
        "tooltip": "none",
        "filename": "cuadro.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "no": {
        "coordinates": (545, 120),
        "tooltip": "none",
        "filename": "cuadro.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "check_si": {
        "coordinates": (430, 120),
        "tooltip": "none",
        "filename": "cuadro-1.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "check_no": {
        "coordinates": (540, 120),
        "tooltip": "none",
        "filename": "cuadro-1.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "boton_nina": {
        "coordinates": (430, 200),
        "tooltip": "none",
        "filename": "cuadro.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "boton_nino": {
        "coordinates": (540, 200),
        "tooltip": "none",
        "filename": "cuadro.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "boton_nina_sel": {
        "coordinates": (430, 200),
        "tooltip": "none",
        "filename": "cuadro-1.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "boton_nino_sel": {
        "coordinates": (540, 200),
        "tooltip": "none",
        "filename": "cuadro-1.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "hoja": {
        "coordinates": (499, 370),
        "tooltip": "Velocidad",
        "filename": "hoja.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "amarillo": {
        "coordinates": (425, 295),
        "tooltip": "Amarillo",
        "filename": "amarilla.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "rosado": {
        "coordinates": (485, 295),
        "tooltip": "Rosado",
        "filename": "rosada.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "rojo": {
        "coordinates": (485, 295),
        "tooltip": "Rojo",
        "filename": "roja.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "v_hombre": {
        "coordinates": (545, 295),
        "tooltip": "Verde",
        "filename": "verdeh.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
    "v_mujer": {
        "coordinates": (545, 295),
        "tooltip": "Verde",
        "filename": "verdem.png",
        "frames": 1,
        "colorkey": None,
        "loop": False,
        "frame_speed": 1,
    },
}
