#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: sembrando-para-el-futuro
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2013, 2014 José Francisco Guerrero <jsfrncscg@gmail.com>
#  (C) 2013, 2014 Homero Salvador Hernández <hsh283@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="sembrando-para-el-futuro"

case ${1} in

	configure)

	chmod +x /usr/share/sembrando-para-el-futuro/presentacion/inicio.py
	;;

        abort-upgrade|abort-remove|abort-deconfigure)

        ;;

        *)

                echo "postinst no reconoce el argumento '"${1}"'" >&2
                exit 1

        ;;

esac

#DEBHELPER#

exit 0
